# Configuration materielle
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Micro-ROS
CONFIG_MICROROS=y
CONFIG_CPP=y
CONFIG_STD_CPP14=y
CONFIG_POSIX_API=y
CONFIG_POSIX_CLOCK=y

# Optimisation de la mémoire
CONFIG_HEAP_MEM_POOL_SIZE=1536
CONFIG_MAIN_STACK_SIZE=256

# Configuration de Micro-ROS
CONFIG_MICROROS_NODES="1"
CONFIG_MICROROS_PUBLISHERS="1"
CONFIG_MICROROS_SUBSCRIBERS="0"
CONFIG_MICROROS_SERVERS="0"
CONFIG_MICROROS_CLIENTS="0"
CONFIG_MICROROS_RMW_HISTORIC="1"
CONFIG_MICROROS_XRCE_DDS_HISTORIC="1"
CONFIG_MICROROS_XRCE_DDS_MTU="64"

# Configuration des piles pour les threads
CONFIG_ISR_STACK_SIZE=512
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=256
CONFIG_IDLE_STACK_SIZE=256

# Désactivation de la console et des logs pour économiser de la mémoire
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n