# # --- CONFIGURATION MATERIELLE ---
# CONFIG_GPIO=y
# CONFIG_I2C=y
# CONFIG_SERIAL=y

# # --- COMMUNICATION (Vitale pour l'USB et Micro-ROS) ---
# CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y
# CONFIG_LOG=n

# # --- MOTEUR MICRO-ROS & POSIX ---
# CONFIG_MICROROS=y
# CONFIG_CPP=y

# # --- OPTIMISATION RAM (Nucleo = 20 Ko) ---
# CONFIG_HEAP_MEM_POOL_SIZE=2048
# CONFIG_MAIN_STACK_SIZE=512
# CONFIG_ISR_STACK_SIZE=512
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
# CONFIG_IDLE_STACK_SIZE=256

# # --- BRIDAGE MICRO-ROS (Régime sec) ---
# CONFIG_MICROROS_NODES="1"
# CONFIG_MICROROS_PUBLISHERS="1"
# CONFIG_MICROROS_SUBSCRIBERS="0"
# CONFIG_MICROROS_SERVERS="0"
# CONFIG_MICROROS_CLIENTS="0"
# CONFIG_MICROROS_RMW_HISTORIC="1"
# CONFIG_MICROROS_XRCE_DDS_HISTORIC="1"
# CONFIG_MICROROS_XRCE_DDS_MTU="64"

# --- CONFIGURATION MATERIELLE ---
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# --- CONFIGURATION MICRO-ROS ---
CONFIG_MICROROS=y
CONFIG_CPP=y
CONFIG_STD_CPP14=y
CONFIG_POSIX_API=y
CONFIG_POSIX_CLOCK=y

# --- OPTIMISATION RAM (Squeeze dans 20 Ko) ---
CONFIG_HEAP_MEM_POOL_SIZE=1536
CONFIG_MAIN_STACK_SIZE=256

# --- BRIDAGE MICRO-ROS (Régime sec) ---
CONFIG_MICROROS_NODES="1"
CONFIG_MICROROS_PUBLISHERS="1"
CONFIG_MICROROS_SUBSCRIBERS="0"
CONFIG_MICROROS_SERVERS="0"
CONFIG_MICROROS_CLIENTS="0"
CONFIG_MICROROS_RMW_HISTORIC="1"
CONFIG_MICROROS_XRCE_DDS_HISTORIC="1"
CONFIG_MICROROS_XRCE_DDS_MTU="64"

# --- OPTIMISATION DU SYSTEME CACHE DE ZEPHYR ---
CONFIG_ISR_STACK_SIZE=512
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=256
CONFIG_IDLE_STACK_SIZE=256

# --- DESACTIVATION DE LA CONSOLE TEXTE & LOGS (Gain : ~1.5 Ko) ---
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n